// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl99YLT71gUzo2ivw7XMqoCh8tnNNJGC0',
    appId: '1:731893456693:web:84931cf4db3b3f2807767c',
    messagingSenderId: '731893456693',
    projectId: 'myportfolio-50031',
    authDomain: 'myportfolio-50031.firebaseapp.com',
    storageBucket: 'myportfolio-50031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_81GxNmBhzq6fdpXxF8OIPfHC3JnkGk',
    appId: '1:731893456693:android:cdd76f845f7b163707767c',
    messagingSenderId: '731893456693',
    projectId: 'myportfolio-50031',
    storageBucket: 'myportfolio-50031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2Ymmoj-Ee8qYutnEMGfaJNC-OyW63fU',
    appId: '1:731893456693:ios:5137f0cbf96b9ac407767c',
    messagingSenderId: '731893456693',
    projectId: 'myportfolio-50031',
    storageBucket: 'myportfolio-50031.firebasestorage.app',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT2Ymmoj-Ee8qYutnEMGfaJNC-OyW63fU',
    appId: '1:731893456693:ios:5137f0cbf96b9ac407767c',
    messagingSenderId: '731893456693',
    projectId: 'myportfolio-50031',
    storageBucket: 'myportfolio-50031.firebasestorage.app',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl99YLT71gUzo2ivw7XMqoCh8tnNNJGC0',
    appId: '1:731893456693:web:9439448e53c1af4507767c',
    messagingSenderId: '731893456693',
    projectId: 'myportfolio-50031',
    authDomain: 'myportfolio-50031.firebaseapp.com',
    storageBucket: 'myportfolio-50031.firebasestorage.app',
  );
}
